version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/ts-isomorphic/" # Location of package manifests
    directory: "/packages/ts-backend/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    target-branch: dev