/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SystemsRouteRouteImport } from './routes/systems/route'
import { Route as SpeciesRouteRouteImport } from './routes/species/route'
import { Route as ParcelsRouteRouteImport } from './routes/parcels/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemsIndexRouteImport } from './routes/systems/index'
import { Route as SpeciesIndexRouteImport } from './routes/species/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SpeciesNewRouteImport } from './routes/species/new'
import { Route as SystemsSystemIdIndexRouteImport } from './routes/systems/$systemId/index'
import { Route as SpeciesSpeciesIdIndexRouteImport } from './routes/species/$speciesId/index'
import { Route as ScenarioPreviewScenarioIdIndexRouteImport } from './routes/scenario-preview/$scenarioId/index'
import { Route as ParcelsParcelIdIndexRouteImport } from './routes/parcels/$parcelId/index'
import { Route as FarmScenarioPreviewConfigIdIndexRouteImport } from './routes/farm-scenario-preview/$configId/index'
import { Route as AdminFarmerAdvisorSurveyIndexRouteImport } from './routes/admin/farmer-advisor-survey/index'
import { Route as AdminAdvisorRequestsIndexRouteImport } from './routes/admin/advisor-requests/index'
import { Route as SystemsSystemIdEditRouteImport } from './routes/systems/$systemId/edit'
import { Route as SpeciesSpeciesIdEditRouteImport } from './routes/species/$speciesId/edit'
import { Route as ParcelsParcelIdLayersRouteImport } from './routes/parcels/$parcelId/layers'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SpeciesSpeciesIdNutrientsNewRouteImport } from './routes/species/$speciesId/nutrients/new'
import { Route as SpeciesSpeciesIdActivitiesNewRouteImport } from './routes/species/$speciesId/activities/new'
import { Route as SpeciesSpeciesIdActivitiesEditRouteImport } from './routes/species/$speciesId/activities/edit'
import { Route as ParcelsParcelIdModelsModelIdIndexRouteImport } from './routes/parcels/$parcelId/models/$modelId/index'
import { Route as ParcelsParcelIdLayersLayerIdIndexRouteImport } from './routes/parcels/$parcelId/layers/$layerId/index'
import { Route as ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRouteImport } from './routes/parcels/$parcelId/farm-scenario/$farmScenarioId/index'
import { Route as ParcelsParcelIdLayersLayerIdProjectsRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects'
import { Route as ParcelsParcelIdLayersLayerIdLayoutRouteImport } from './routes/parcels/$parcelId/layers/$layerId/layout'
import { Route as ParcelsParcelIdLayersLayerIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/edit'
import { Route as ApiUpdaterTargetArchCurrent_versionRouteImport } from './routes/api/updater/$target/$arch/$current_version'
import { Route as ApiProjectsProjectIdFinancialsActivitiesRouteImport } from './routes/api/projects/$projectId/financials/activities'
import { Route as ParcelsParcelIdLayersLayerIdSequencesNewRouteImport } from './routes/parcels/$parcelId/layers/$layerId/sequences/new'
import { Route as ParcelsParcelIdLayersLayerIdRowNewIndexRouteImport } from './routes/parcels/$parcelId/layers/$layerId/row/new/index'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/index'
import { Route as ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
import { Route as ParcelsParcelIdLayersLayerIdRowRowIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/index'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/index'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
import { Route as ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRouteImport } from './routes/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRouteRoute = SystemsRouteRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRouteRoute = SpeciesRouteRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRouteRoute = ParcelsRouteRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsIndexRoute = SystemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpeciesRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesNewRoute = SpeciesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SpeciesRouteRoute,
} as any)
const SystemsSystemIdIndexRoute = SystemsSystemIdIndexRouteImport.update({
  id: '/$systemId/',
  path: '/$systemId/',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const SpeciesSpeciesIdIndexRoute = SpeciesSpeciesIdIndexRouteImport.update({
  id: '/$speciesId/',
  path: '/$speciesId/',
  getParentRoute: () => SpeciesRouteRoute,
} as any)
const ScenarioPreviewScenarioIdIndexRoute =
  ScenarioPreviewScenarioIdIndexRouteImport.update({
    id: '/scenario-preview/$scenarioId/',
    path: '/scenario-preview/$scenarioId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParcelsParcelIdIndexRoute = ParcelsParcelIdIndexRouteImport.update({
  id: '/$parcelId/',
  path: '/$parcelId/',
  getParentRoute: () => ParcelsRouteRoute,
} as any)
const FarmScenarioPreviewConfigIdIndexRoute =
  FarmScenarioPreviewConfigIdIndexRouteImport.update({
    id: '/farm-scenario-preview/$configId/',
    path: '/farm-scenario-preview/$configId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminFarmerAdvisorSurveyIndexRoute =
  AdminFarmerAdvisorSurveyIndexRouteImport.update({
    id: '/admin/farmer-advisor-survey/',
    path: '/admin/farmer-advisor-survey/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdvisorRequestsIndexRoute =
  AdminAdvisorRequestsIndexRouteImport.update({
    id: '/admin/advisor-requests/',
    path: '/admin/advisor-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SystemsSystemIdEditRoute = SystemsSystemIdEditRouteImport.update({
  id: '/$systemId/edit',
  path: '/$systemId/edit',
  getParentRoute: () => SystemsRouteRoute,
} as any)
const SpeciesSpeciesIdEditRoute = SpeciesSpeciesIdEditRouteImport.update({
  id: '/$speciesId/edit',
  path: '/$speciesId/edit',
  getParentRoute: () => SpeciesRouteRoute,
} as any)
const ParcelsParcelIdLayersRoute = ParcelsParcelIdLayersRouteImport.update({
  id: '/$parcelId/layers',
  path: '/$parcelId/layers',
  getParentRoute: () => ParcelsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesSpeciesIdNutrientsNewRoute =
  SpeciesSpeciesIdNutrientsNewRouteImport.update({
    id: '/$speciesId/nutrients/new',
    path: '/$speciesId/nutrients/new',
    getParentRoute: () => SpeciesRouteRoute,
  } as any)
const SpeciesSpeciesIdActivitiesNewRoute =
  SpeciesSpeciesIdActivitiesNewRouteImport.update({
    id: '/$speciesId/activities/new',
    path: '/$speciesId/activities/new',
    getParentRoute: () => SpeciesRouteRoute,
  } as any)
const SpeciesSpeciesIdActivitiesEditRoute =
  SpeciesSpeciesIdActivitiesEditRouteImport.update({
    id: '/$speciesId/activities/edit',
    path: '/$speciesId/activities/edit',
    getParentRoute: () => SpeciesRouteRoute,
  } as any)
const ParcelsParcelIdModelsModelIdIndexRoute =
  ParcelsParcelIdModelsModelIdIndexRouteImport.update({
    id: '/$parcelId/models/$modelId/',
    path: '/$parcelId/models/$modelId/',
    getParentRoute: () => ParcelsRouteRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdIndexRoute =
  ParcelsParcelIdLayersLayerIdIndexRouteImport.update({
    id: '/$layerId/',
    path: '/$layerId/',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute =
  ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRouteImport.update({
    id: '/$parcelId/farm-scenario/$farmScenarioId/',
    path: '/$parcelId/farm-scenario/$farmScenarioId/',
    getParentRoute: () => ParcelsRouteRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsRoute =
  ParcelsParcelIdLayersLayerIdProjectsRouteImport.update({
    id: '/$layerId/projects',
    path: '/$layerId/projects',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdLayoutRoute =
  ParcelsParcelIdLayersLayerIdLayoutRouteImport.update({
    id: '/$layerId/layout',
    path: '/$layerId/layout',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdEditRoute =
  ParcelsParcelIdLayersLayerIdEditRouteImport.update({
    id: '/$layerId/edit',
    path: '/$layerId/edit',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ApiUpdaterTargetArchCurrent_versionRoute =
  ApiUpdaterTargetArchCurrent_versionRouteImport.update({
    id: '/api/updater/$target/$arch/$current_version',
    path: '/api/updater/$target/$arch/$current_version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsProjectIdFinancialsActivitiesRoute =
  ApiProjectsProjectIdFinancialsActivitiesRouteImport.update({
    id: '/api/projects/$projectId/financials/activities',
    path: '/api/projects/$projectId/financials/activities',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParcelsParcelIdLayersLayerIdSequencesNewRoute =
  ParcelsParcelIdLayersLayerIdSequencesNewRouteImport.update({
    id: '/$layerId/sequences/new',
    path: '/$layerId/sequences/new',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdRowNewIndexRoute =
  ParcelsParcelIdLayersLayerIdRowNewIndexRouteImport.update({
    id: '/$layerId/row/new/',
    path: '/$layerId/row/new/',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute =
  ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRouteImport.update({
    id: '/$layerId/sequences/$sequenceId/edit',
    path: '/$layerId/sequences/$sequenceId/edit',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdRowRowIdEditRoute =
  ParcelsParcelIdLayersLayerIdRowRowIdEditRouteImport.update({
    id: '/$layerId/row/$rowId/edit',
    path: '/$layerId/row/$rowId/edit',
    getParentRoute: () => ParcelsParcelIdLayersRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRouteImport.update({
    id: '/$projectId/mysystems',
    path: '/$projectId/mysystems',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRouteImport.update(
    {
      id: '/$projectId/generateestablishment',
      path: '/$projectId/generateestablishment',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )
const ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRouteImport.update({
    id: '/$projectId/financials',
    path: '/$projectId/financials',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRouteImport.update({
    id: '/$projectId/backup',
    path: '/$projectId/backup',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRouteImport.update({
    id: '/$projectId/assets',
    path: '/$projectId/assets',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRouteImport.update({
    id: '/$projectId/sequences/new',
    path: '/$projectId/sequences/new',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRouteImport.update({
    id: '/$projectId/rotations/new',
    path: '/$projectId/rotations/new',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRouteImport.update(
    {
      id: '/$projectId/systems/$systemId/',
      path: '/$projectId/systems/$systemId/',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )
const ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRouteImport.update({
    id: '/$projectId/row/new/',
    path: '/$projectId/row/new/',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRouteImport.update(
    {
      id: '/$projectId/systems/$systemId/edit',
      path: '/$projectId/systems/$systemId/edit',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )
const ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRouteImport.update(
    {
      id: '/$projectId/sequences/$sequenceId/edit',
      path: '/$projectId/sequences/$sequenceId/edit',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )
const ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRouteImport.update({
    id: '/$projectId/row/$rowId/edit',
    path: '/$projectId/row/$rowId/edit',
    getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
  } as any)
const ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRouteImport.update(
    {
      id: '/$projectId/rotations/$rotationId/edit',
      path: '/$projectId/rotations/$rotationId/edit',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )
const ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute =
  ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRouteImport.update(
    {
      id: '/$projectId/areas/$areaId/edit',
      path: '/$projectId/areas/$areaId/edit',
      getParentRoute: () => ParcelsParcelIdLayersLayerIdProjectsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRouteRouteWithChildren
  '/species': typeof SpeciesRouteRouteWithChildren
  '/systems': typeof SystemsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/species/new': typeof SpeciesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/species/': typeof SpeciesIndexRoute
  '/systems/': typeof SystemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/parcels/$parcelId/layers': typeof ParcelsParcelIdLayersRouteWithChildren
  '/species/$speciesId/edit': typeof SpeciesSpeciesIdEditRoute
  '/systems/$systemId/edit': typeof SystemsSystemIdEditRoute
  '/admin/advisor-requests/': typeof AdminAdvisorRequestsIndexRoute
  '/admin/farmer-advisor-survey/': typeof AdminFarmerAdvisorSurveyIndexRoute
  '/farm-scenario-preview/$configId/': typeof FarmScenarioPreviewConfigIdIndexRoute
  '/parcels/$parcelId/': typeof ParcelsParcelIdIndexRoute
  '/scenario-preview/$scenarioId/': typeof ScenarioPreviewScenarioIdIndexRoute
  '/species/$speciesId/': typeof SpeciesSpeciesIdIndexRoute
  '/systems/$systemId/': typeof SystemsSystemIdIndexRoute
  '/species/$speciesId/activities/edit': typeof SpeciesSpeciesIdActivitiesEditRoute
  '/species/$speciesId/activities/new': typeof SpeciesSpeciesIdActivitiesNewRoute
  '/species/$speciesId/nutrients/new': typeof SpeciesSpeciesIdNutrientsNewRoute
  '/api/projects/$projectId/financials/activities': typeof ApiProjectsProjectIdFinancialsActivitiesRoute
  '/api/updater/$target/$arch/$current_version': typeof ApiUpdaterTargetArchCurrent_versionRoute
  '/parcels/$parcelId/layers/$layerId/edit': typeof ParcelsParcelIdLayersLayerIdEditRoute
  '/parcels/$parcelId/layers/$layerId/layout': typeof ParcelsParcelIdLayersLayerIdLayoutRoute
  '/parcels/$parcelId/layers/$layerId/projects': typeof ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren
  '/parcels/$parcelId/farm-scenario/$farmScenarioId/': typeof ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/': typeof ParcelsParcelIdLayersLayerIdIndexRoute
  '/parcels/$parcelId/models/$modelId/': typeof ParcelsParcelIdModelsModelIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/sequences/new': typeof ParcelsParcelIdLayersLayerIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute
  '/parcels/$parcelId/layers/$layerId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/row/new/': typeof ParcelsParcelIdLayersLayerIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/species/new': typeof SpeciesNewRoute
  '/admin': typeof AdminIndexRoute
  '/species': typeof SpeciesIndexRoute
  '/systems': typeof SystemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/parcels/$parcelId/layers': typeof ParcelsParcelIdLayersRouteWithChildren
  '/species/$speciesId/edit': typeof SpeciesSpeciesIdEditRoute
  '/systems/$systemId/edit': typeof SystemsSystemIdEditRoute
  '/admin/advisor-requests': typeof AdminAdvisorRequestsIndexRoute
  '/admin/farmer-advisor-survey': typeof AdminFarmerAdvisorSurveyIndexRoute
  '/farm-scenario-preview/$configId': typeof FarmScenarioPreviewConfigIdIndexRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdIndexRoute
  '/scenario-preview/$scenarioId': typeof ScenarioPreviewScenarioIdIndexRoute
  '/species/$speciesId': typeof SpeciesSpeciesIdIndexRoute
  '/systems/$systemId': typeof SystemsSystemIdIndexRoute
  '/species/$speciesId/activities/edit': typeof SpeciesSpeciesIdActivitiesEditRoute
  '/species/$speciesId/activities/new': typeof SpeciesSpeciesIdActivitiesNewRoute
  '/species/$speciesId/nutrients/new': typeof SpeciesSpeciesIdNutrientsNewRoute
  '/api/projects/$projectId/financials/activities': typeof ApiProjectsProjectIdFinancialsActivitiesRoute
  '/api/updater/$target/$arch/$current_version': typeof ApiUpdaterTargetArchCurrent_versionRoute
  '/parcels/$parcelId/layers/$layerId/edit': typeof ParcelsParcelIdLayersLayerIdEditRoute
  '/parcels/$parcelId/layers/$layerId/layout': typeof ParcelsParcelIdLayersLayerIdLayoutRoute
  '/parcels/$parcelId/layers/$layerId/projects': typeof ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren
  '/parcels/$parcelId/farm-scenario/$farmScenarioId': typeof ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute
  '/parcels/$parcelId/layers/$layerId': typeof ParcelsParcelIdLayersLayerIdIndexRoute
  '/parcels/$parcelId/models/$modelId': typeof ParcelsParcelIdModelsModelIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/sequences/new': typeof ParcelsParcelIdLayersLayerIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute
  '/parcels/$parcelId/layers/$layerId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/row/new': typeof ParcelsParcelIdLayersLayerIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parcels': typeof ParcelsRouteRouteWithChildren
  '/species': typeof SpeciesRouteRouteWithChildren
  '/systems': typeof SystemsRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/species/new': typeof SpeciesNewRoute
  '/admin/': typeof AdminIndexRoute
  '/species/': typeof SpeciesIndexRoute
  '/systems/': typeof SystemsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/parcels/$parcelId/layers': typeof ParcelsParcelIdLayersRouteWithChildren
  '/species/$speciesId/edit': typeof SpeciesSpeciesIdEditRoute
  '/systems/$systemId/edit': typeof SystemsSystemIdEditRoute
  '/admin/advisor-requests/': typeof AdminAdvisorRequestsIndexRoute
  '/admin/farmer-advisor-survey/': typeof AdminFarmerAdvisorSurveyIndexRoute
  '/farm-scenario-preview/$configId/': typeof FarmScenarioPreviewConfigIdIndexRoute
  '/parcels/$parcelId/': typeof ParcelsParcelIdIndexRoute
  '/scenario-preview/$scenarioId/': typeof ScenarioPreviewScenarioIdIndexRoute
  '/species/$speciesId/': typeof SpeciesSpeciesIdIndexRoute
  '/systems/$systemId/': typeof SystemsSystemIdIndexRoute
  '/species/$speciesId/activities/edit': typeof SpeciesSpeciesIdActivitiesEditRoute
  '/species/$speciesId/activities/new': typeof SpeciesSpeciesIdActivitiesNewRoute
  '/species/$speciesId/nutrients/new': typeof SpeciesSpeciesIdNutrientsNewRoute
  '/api/projects/$projectId/financials/activities': typeof ApiProjectsProjectIdFinancialsActivitiesRoute
  '/api/updater/$target/$arch/$current_version': typeof ApiUpdaterTargetArchCurrent_versionRoute
  '/parcels/$parcelId/layers/$layerId/edit': typeof ParcelsParcelIdLayersLayerIdEditRoute
  '/parcels/$parcelId/layers/$layerId/layout': typeof ParcelsParcelIdLayersLayerIdLayoutRoute
  '/parcels/$parcelId/layers/$layerId/projects': typeof ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren
  '/parcels/$parcelId/farm-scenario/$farmScenarioId/': typeof ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/': typeof ParcelsParcelIdLayersLayerIdIndexRoute
  '/parcels/$parcelId/models/$modelId/': typeof ParcelsParcelIdModelsModelIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/sequences/new': typeof ParcelsParcelIdLayersLayerIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute
  '/parcels/$parcelId/layers/$layerId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute
  '/parcels/$parcelId/layers/$layerId/row/new/': typeof ParcelsParcelIdLayersLayerIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute
  '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/': typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/parcels'
    | '/species'
    | '/systems'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/species/new'
    | '/admin/'
    | '/species/'
    | '/systems/'
    | '/api/auth/$'
    | '/parcels/$parcelId/layers'
    | '/species/$speciesId/edit'
    | '/systems/$systemId/edit'
    | '/admin/advisor-requests/'
    | '/admin/farmer-advisor-survey/'
    | '/farm-scenario-preview/$configId/'
    | '/parcels/$parcelId/'
    | '/scenario-preview/$scenarioId/'
    | '/species/$speciesId/'
    | '/systems/$systemId/'
    | '/species/$speciesId/activities/edit'
    | '/species/$speciesId/activities/new'
    | '/species/$speciesId/nutrients/new'
    | '/api/projects/$projectId/financials/activities'
    | '/api/updater/$target/$arch/$current_version'
    | '/parcels/$parcelId/layers/$layerId/edit'
    | '/parcels/$parcelId/layers/$layerId/layout'
    | '/parcels/$parcelId/layers/$layerId/projects'
    | '/parcels/$parcelId/farm-scenario/$farmScenarioId/'
    | '/parcels/$parcelId/layers/$layerId/'
    | '/parcels/$parcelId/models/$modelId/'
    | '/parcels/$parcelId/layers/$layerId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
    | '/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/'
    | '/parcels/$parcelId/layers/$layerId/row/new/'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/parcels'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/species/new'
    | '/admin'
    | '/species'
    | '/systems'
    | '/api/auth/$'
    | '/parcels/$parcelId/layers'
    | '/species/$speciesId/edit'
    | '/systems/$systemId/edit'
    | '/admin/advisor-requests'
    | '/admin/farmer-advisor-survey'
    | '/farm-scenario-preview/$configId'
    | '/parcels/$parcelId'
    | '/scenario-preview/$scenarioId'
    | '/species/$speciesId'
    | '/systems/$systemId'
    | '/species/$speciesId/activities/edit'
    | '/species/$speciesId/activities/new'
    | '/species/$speciesId/nutrients/new'
    | '/api/projects/$projectId/financials/activities'
    | '/api/updater/$target/$arch/$current_version'
    | '/parcels/$parcelId/layers/$layerId/edit'
    | '/parcels/$parcelId/layers/$layerId/layout'
    | '/parcels/$parcelId/layers/$layerId/projects'
    | '/parcels/$parcelId/farm-scenario/$farmScenarioId'
    | '/parcels/$parcelId/layers/$layerId'
    | '/parcels/$parcelId/models/$modelId'
    | '/parcels/$parcelId/layers/$layerId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
    | '/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId'
    | '/parcels/$parcelId/layers/$layerId/row/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId'
  id:
    | '__root__'
    | '/'
    | '/parcels'
    | '/species'
    | '/systems'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/species/new'
    | '/admin/'
    | '/species/'
    | '/systems/'
    | '/api/auth/$'
    | '/parcels/$parcelId/layers'
    | '/species/$speciesId/edit'
    | '/systems/$systemId/edit'
    | '/admin/advisor-requests/'
    | '/admin/farmer-advisor-survey/'
    | '/farm-scenario-preview/$configId/'
    | '/parcels/$parcelId/'
    | '/scenario-preview/$scenarioId/'
    | '/species/$speciesId/'
    | '/systems/$systemId/'
    | '/species/$speciesId/activities/edit'
    | '/species/$speciesId/activities/new'
    | '/species/$speciesId/nutrients/new'
    | '/api/projects/$projectId/financials/activities'
    | '/api/updater/$target/$arch/$current_version'
    | '/parcels/$parcelId/layers/$layerId/edit'
    | '/parcels/$parcelId/layers/$layerId/layout'
    | '/parcels/$parcelId/layers/$layerId/projects'
    | '/parcels/$parcelId/farm-scenario/$farmScenarioId/'
    | '/parcels/$parcelId/layers/$layerId/'
    | '/parcels/$parcelId/models/$modelId/'
    | '/parcels/$parcelId/layers/$layerId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
    | '/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/'
    | '/parcels/$parcelId/layers/$layerId/row/new/'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/'
    | '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParcelsRouteRoute: typeof ParcelsRouteRouteWithChildren
  SpeciesRouteRoute: typeof SpeciesRouteRouteWithChildren
  SystemsRouteRoute: typeof SystemsRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AdminAdvisorRequestsIndexRoute: typeof AdminAdvisorRequestsIndexRoute
  AdminFarmerAdvisorSurveyIndexRoute: typeof AdminFarmerAdvisorSurveyIndexRoute
  FarmScenarioPreviewConfigIdIndexRoute: typeof FarmScenarioPreviewConfigIdIndexRoute
  ScenarioPreviewScenarioIdIndexRoute: typeof ScenarioPreviewScenarioIdIndexRoute
  ApiProjectsProjectIdFinancialsActivitiesRoute: typeof ApiProjectsProjectIdFinancialsActivitiesRoute
  ApiUpdaterTargetArchCurrent_versionRoute: typeof ApiUpdaterTargetArchCurrent_versionRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/': {
      id: '/systems/'
      path: '/'
      fullPath: '/systems/'
      preLoaderRoute: typeof SystemsIndexRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/species/': {
      id: '/species/'
      path: '/'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/new': {
      id: '/species/new'
      path: '/new'
      fullPath: '/species/new'
      preLoaderRoute: typeof SpeciesNewRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/systems/$systemId/': {
      id: '/systems/$systemId/'
      path: '/$systemId'
      fullPath: '/systems/$systemId/'
      preLoaderRoute: typeof SystemsSystemIdIndexRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/species/$speciesId/': {
      id: '/species/$speciesId/'
      path: '/$speciesId'
      fullPath: '/species/$speciesId/'
      preLoaderRoute: typeof SpeciesSpeciesIdIndexRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/scenario-preview/$scenarioId/': {
      id: '/scenario-preview/$scenarioId/'
      path: '/scenario-preview/$scenarioId'
      fullPath: '/scenario-preview/$scenarioId/'
      preLoaderRoute: typeof ScenarioPreviewScenarioIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels/$parcelId/': {
      id: '/parcels/$parcelId/'
      path: '/$parcelId'
      fullPath: '/parcels/$parcelId/'
      preLoaderRoute: typeof ParcelsParcelIdIndexRouteImport
      parentRoute: typeof ParcelsRouteRoute
    }
    '/farm-scenario-preview/$configId/': {
      id: '/farm-scenario-preview/$configId/'
      path: '/farm-scenario-preview/$configId'
      fullPath: '/farm-scenario-preview/$configId/'
      preLoaderRoute: typeof FarmScenarioPreviewConfigIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/farmer-advisor-survey/': {
      id: '/admin/farmer-advisor-survey/'
      path: '/admin/farmer-advisor-survey'
      fullPath: '/admin/farmer-advisor-survey/'
      preLoaderRoute: typeof AdminFarmerAdvisorSurveyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/advisor-requests/': {
      id: '/admin/advisor-requests/'
      path: '/admin/advisor-requests'
      fullPath: '/admin/advisor-requests/'
      preLoaderRoute: typeof AdminAdvisorRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems/$systemId/edit': {
      id: '/systems/$systemId/edit'
      path: '/$systemId/edit'
      fullPath: '/systems/$systemId/edit'
      preLoaderRoute: typeof SystemsSystemIdEditRouteImport
      parentRoute: typeof SystemsRouteRoute
    }
    '/species/$speciesId/edit': {
      id: '/species/$speciesId/edit'
      path: '/$speciesId/edit'
      fullPath: '/species/$speciesId/edit'
      preLoaderRoute: typeof SpeciesSpeciesIdEditRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/parcels/$parcelId/layers': {
      id: '/parcels/$parcelId/layers'
      path: '/$parcelId/layers'
      fullPath: '/parcels/$parcelId/layers'
      preLoaderRoute: typeof ParcelsParcelIdLayersRouteImport
      parentRoute: typeof ParcelsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$speciesId/nutrients/new': {
      id: '/species/$speciesId/nutrients/new'
      path: '/$speciesId/nutrients/new'
      fullPath: '/species/$speciesId/nutrients/new'
      preLoaderRoute: typeof SpeciesSpeciesIdNutrientsNewRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/species/$speciesId/activities/new': {
      id: '/species/$speciesId/activities/new'
      path: '/$speciesId/activities/new'
      fullPath: '/species/$speciesId/activities/new'
      preLoaderRoute: typeof SpeciesSpeciesIdActivitiesNewRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/species/$speciesId/activities/edit': {
      id: '/species/$speciesId/activities/edit'
      path: '/$speciesId/activities/edit'
      fullPath: '/species/$speciesId/activities/edit'
      preLoaderRoute: typeof SpeciesSpeciesIdActivitiesEditRouteImport
      parentRoute: typeof SpeciesRouteRoute
    }
    '/parcels/$parcelId/models/$modelId/': {
      id: '/parcels/$parcelId/models/$modelId/'
      path: '/$parcelId/models/$modelId'
      fullPath: '/parcels/$parcelId/models/$modelId/'
      preLoaderRoute: typeof ParcelsParcelIdModelsModelIdIndexRouteImport
      parentRoute: typeof ParcelsRouteRoute
    }
    '/parcels/$parcelId/layers/$layerId/': {
      id: '/parcels/$parcelId/layers/$layerId/'
      path: '/$layerId'
      fullPath: '/parcels/$parcelId/layers/$layerId/'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdIndexRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/farm-scenario/$farmScenarioId/': {
      id: '/parcels/$parcelId/farm-scenario/$farmScenarioId/'
      path: '/$parcelId/farm-scenario/$farmScenarioId'
      fullPath: '/parcels/$parcelId/farm-scenario/$farmScenarioId/'
      preLoaderRoute: typeof ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRouteImport
      parentRoute: typeof ParcelsRouteRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects': {
      id: '/parcels/$parcelId/layers/$layerId/projects'
      path: '/$layerId/projects'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/layout': {
      id: '/parcels/$parcelId/layers/$layerId/layout'
      path: '/$layerId/layout'
      fullPath: '/parcels/$parcelId/layers/$layerId/layout'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdLayoutRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/edit'
      path: '/$layerId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/api/updater/$target/$arch/$current_version': {
      id: '/api/updater/$target/$arch/$current_version'
      path: '/api/updater/$target/$arch/$current_version'
      fullPath: '/api/updater/$target/$arch/$current_version'
      preLoaderRoute: typeof ApiUpdaterTargetArchCurrent_versionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$projectId/financials/activities': {
      id: '/api/projects/$projectId/financials/activities'
      path: '/api/projects/$projectId/financials/activities'
      fullPath: '/api/projects/$projectId/financials/activities'
      preLoaderRoute: typeof ApiProjectsProjectIdFinancialsActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels/$parcelId/layers/$layerId/sequences/new': {
      id: '/parcels/$parcelId/layers/$layerId/sequences/new'
      path: '/$layerId/sequences/new'
      fullPath: '/parcels/$parcelId/layers/$layerId/sequences/new'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdSequencesNewRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/row/new/': {
      id: '/parcels/$parcelId/layers/$layerId/row/new/'
      path: '/$layerId/row/new'
      fullPath: '/parcels/$parcelId/layers/$layerId/row/new/'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdRowNewIndexRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
      path: '/$layerId/sequences/$sequenceId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/sequences/$sequenceId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/row/$rowId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
      path: '/$layerId/row/$rowId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/row/$rowId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdRowRowIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
      path: '/$projectId/mysystems'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/mysystems'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
      path: '/$projectId/generateestablishment'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/generateestablishment'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
      path: '/$projectId/financials'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/financials'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
      path: '/$projectId/backup'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/backup'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
      path: '/$projectId/assets'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/assets'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
      path: '/$projectId/sequences/new'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/new'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
      path: '/$projectId/rotations/new'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/new'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/'
      path: '/$projectId/systems/$systemId'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/'
      path: '/$projectId/row/new'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/new/'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
      path: '/$projectId/systems/$systemId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/systems/$systemId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
      path: '/$projectId/sequences/$sequenceId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/sequences/$sequenceId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
      path: '/$projectId/row/$rowId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/row/$rowId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
      path: '/$projectId/rotations/$rotationId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/rotations/$rotationId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
    '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit': {
      id: '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'
      path: '/$projectId/areas/$areaId/edit'
      fullPath: '/parcels/$parcelId/layers/$layerId/projects/$projectId/areas/$areaId/edit'
      preLoaderRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRouteImport
      parentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRoute
    }
  }
}

interface ParcelsParcelIdLayersLayerIdProjectsRouteChildren {
  ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute
  ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute: typeof ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute
}

const ParcelsParcelIdLayersLayerIdProjectsRouteChildren: ParcelsParcelIdLayersLayerIdProjectsRouteChildren =
  {
    ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdAssetsRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdBackupRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdFinancialsRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdGenerateestablishmentRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdMysystemsRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdIndexRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsNewRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesNewRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdAreasAreaIdEditRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdRotationsRotationIdEditRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdRowRowIdEditRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdSequencesSequenceIdEditRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdEditRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdRowNewIndexRoute,
    ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute:
      ParcelsParcelIdLayersLayerIdProjectsProjectIdSystemsSystemIdIndexRoute,
  }

const ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren =
  ParcelsParcelIdLayersLayerIdProjectsRoute._addFileChildren(
    ParcelsParcelIdLayersLayerIdProjectsRouteChildren,
  )

interface ParcelsParcelIdLayersRouteChildren {
  ParcelsParcelIdLayersLayerIdEditRoute: typeof ParcelsParcelIdLayersLayerIdEditRoute
  ParcelsParcelIdLayersLayerIdLayoutRoute: typeof ParcelsParcelIdLayersLayerIdLayoutRoute
  ParcelsParcelIdLayersLayerIdProjectsRoute: typeof ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren
  ParcelsParcelIdLayersLayerIdIndexRoute: typeof ParcelsParcelIdLayersLayerIdIndexRoute
  ParcelsParcelIdLayersLayerIdSequencesNewRoute: typeof ParcelsParcelIdLayersLayerIdSequencesNewRoute
  ParcelsParcelIdLayersLayerIdRowRowIdEditRoute: typeof ParcelsParcelIdLayersLayerIdRowRowIdEditRoute
  ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute: typeof ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute
  ParcelsParcelIdLayersLayerIdRowNewIndexRoute: typeof ParcelsParcelIdLayersLayerIdRowNewIndexRoute
}

const ParcelsParcelIdLayersRouteChildren: ParcelsParcelIdLayersRouteChildren = {
  ParcelsParcelIdLayersLayerIdEditRoute: ParcelsParcelIdLayersLayerIdEditRoute,
  ParcelsParcelIdLayersLayerIdLayoutRoute:
    ParcelsParcelIdLayersLayerIdLayoutRoute,
  ParcelsParcelIdLayersLayerIdProjectsRoute:
    ParcelsParcelIdLayersLayerIdProjectsRouteWithChildren,
  ParcelsParcelIdLayersLayerIdIndexRoute:
    ParcelsParcelIdLayersLayerIdIndexRoute,
  ParcelsParcelIdLayersLayerIdSequencesNewRoute:
    ParcelsParcelIdLayersLayerIdSequencesNewRoute,
  ParcelsParcelIdLayersLayerIdRowRowIdEditRoute:
    ParcelsParcelIdLayersLayerIdRowRowIdEditRoute,
  ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute:
    ParcelsParcelIdLayersLayerIdSequencesSequenceIdEditRoute,
  ParcelsParcelIdLayersLayerIdRowNewIndexRoute:
    ParcelsParcelIdLayersLayerIdRowNewIndexRoute,
}

const ParcelsParcelIdLayersRouteWithChildren =
  ParcelsParcelIdLayersRoute._addFileChildren(
    ParcelsParcelIdLayersRouteChildren,
  )

interface ParcelsRouteRouteChildren {
  ParcelsParcelIdLayersRoute: typeof ParcelsParcelIdLayersRouteWithChildren
  ParcelsParcelIdIndexRoute: typeof ParcelsParcelIdIndexRoute
  ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute: typeof ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute
  ParcelsParcelIdModelsModelIdIndexRoute: typeof ParcelsParcelIdModelsModelIdIndexRoute
}

const ParcelsRouteRouteChildren: ParcelsRouteRouteChildren = {
  ParcelsParcelIdLayersRoute: ParcelsParcelIdLayersRouteWithChildren,
  ParcelsParcelIdIndexRoute: ParcelsParcelIdIndexRoute,
  ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute:
    ParcelsParcelIdFarmScenarioFarmScenarioIdIndexRoute,
  ParcelsParcelIdModelsModelIdIndexRoute:
    ParcelsParcelIdModelsModelIdIndexRoute,
}

const ParcelsRouteRouteWithChildren = ParcelsRouteRoute._addFileChildren(
  ParcelsRouteRouteChildren,
)

interface SpeciesRouteRouteChildren {
  SpeciesNewRoute: typeof SpeciesNewRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
  SpeciesSpeciesIdEditRoute: typeof SpeciesSpeciesIdEditRoute
  SpeciesSpeciesIdIndexRoute: typeof SpeciesSpeciesIdIndexRoute
  SpeciesSpeciesIdActivitiesEditRoute: typeof SpeciesSpeciesIdActivitiesEditRoute
  SpeciesSpeciesIdActivitiesNewRoute: typeof SpeciesSpeciesIdActivitiesNewRoute
  SpeciesSpeciesIdNutrientsNewRoute: typeof SpeciesSpeciesIdNutrientsNewRoute
}

const SpeciesRouteRouteChildren: SpeciesRouteRouteChildren = {
  SpeciesNewRoute: SpeciesNewRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
  SpeciesSpeciesIdEditRoute: SpeciesSpeciesIdEditRoute,
  SpeciesSpeciesIdIndexRoute: SpeciesSpeciesIdIndexRoute,
  SpeciesSpeciesIdActivitiesEditRoute: SpeciesSpeciesIdActivitiesEditRoute,
  SpeciesSpeciesIdActivitiesNewRoute: SpeciesSpeciesIdActivitiesNewRoute,
  SpeciesSpeciesIdNutrientsNewRoute: SpeciesSpeciesIdNutrientsNewRoute,
}

const SpeciesRouteRouteWithChildren = SpeciesRouteRoute._addFileChildren(
  SpeciesRouteRouteChildren,
)

interface SystemsRouteRouteChildren {
  SystemsIndexRoute: typeof SystemsIndexRoute
  SystemsSystemIdEditRoute: typeof SystemsSystemIdEditRoute
  SystemsSystemIdIndexRoute: typeof SystemsSystemIdIndexRoute
}

const SystemsRouteRouteChildren: SystemsRouteRouteChildren = {
  SystemsIndexRoute: SystemsIndexRoute,
  SystemsSystemIdEditRoute: SystemsSystemIdEditRoute,
  SystemsSystemIdIndexRoute: SystemsSystemIdIndexRoute,
}

const SystemsRouteRouteWithChildren = SystemsRouteRoute._addFileChildren(
  SystemsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParcelsRouteRoute: ParcelsRouteRouteWithChildren,
  SpeciesRouteRoute: SpeciesRouteRouteWithChildren,
  SystemsRouteRoute: SystemsRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AdminAdvisorRequestsIndexRoute: AdminAdvisorRequestsIndexRoute,
  AdminFarmerAdvisorSurveyIndexRoute: AdminFarmerAdvisorSurveyIndexRoute,
  FarmScenarioPreviewConfigIdIndexRoute: FarmScenarioPreviewConfigIdIndexRoute,
  ScenarioPreviewScenarioIdIndexRoute: ScenarioPreviewScenarioIdIndexRoute,
  ApiProjectsProjectIdFinancialsActivitiesRoute:
    ApiProjectsProjectIdFinancialsActivitiesRoute,
  ApiUpdaterTargetArchCurrent_versionRoute:
    ApiUpdaterTargetArchCurrent_versionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
